/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * TilesFST API
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface BrandAdminItem {
  id: number;
  name: string;
  sort_order: number;
  short_name?: string | null;
  english_name?: string | null;
  logo_object_key?: string | null;
  logo_url?: string | null;
  description?: string | null;
  status: string;
  sku_count: number;
  created_at: string;
  updated_at: string;
}

export interface ApiResponseBrandAdminItem {
  code?: number;
  message?: string;
  data?: BrandAdminItem | null;
}

export interface BrandAdminSummary {
  total: number;
  enabled_count: number;
  disabled_count: number;
  unlinked_sku_count: number;
}

export interface BrandAdminListData {
  items: BrandAdminItem[];
  page: number;
  page_size: number;
  total: number;
  summary: BrandAdminSummary;
}

export interface ApiResponseBrandAdminListData {
  code?: number;
  message?: string;
  data?: BrandAdminListData | null;
}

export interface UserProfile {
  id: string;
  username: string;
  display_name: string;
  role: string;
  status: string;
}

export interface LoginData {
  access_token: string;
  token_type?: string;
  expires_in: number;
  user: UserProfile;
}

export interface ApiResponseLoginData {
  code?: number;
  message?: string;
  data?: LoginData | null;
}

export interface LogoutData {
  success?: boolean;
}

export interface ApiResponseLogoutData {
  code?: number;
  message?: string;
  data?: LogoutData | null;
}

export interface ApiResponseNoneType {
  code?: number;
  message?: string;
  /** @nullable */
  data?: null;
}

export interface ResetPasswordData {
  password: string;
}

export interface ApiResponseResetPasswordData {
  code?: number;
  message?: string;
  data?: ResetPasswordData | null;
}

export interface TileCategoryAdminItem {
  id: number;
  parent_id?: number | null;
  name: string;
  code: string;
  sort_order: number;
  level: number;
  description?: string | null;
  status: string;
  sku_count: number;
  path: string;
  created_at: string;
  updated_at: string;
}

export interface ApiResponseTileCategoryAdminItem {
  code?: number;
  message?: string;
  data?: TileCategoryAdminItem | null;
}

export interface TileCategoryAdminSummary {
  total: number;
  enabled_count: number;
  bound_sku_total: number;
  max_level?: number;
}

export interface TileCategoryAdminListData {
  items: TileCategoryAdminItem[];
  page: number;
  page_size: number;
  total: number;
  summary: TileCategoryAdminSummary;
}

export interface ApiResponseTileCategoryAdminListData {
  code?: number;
  message?: string;
  data?: TileCategoryAdminListData | null;
}

export type TileSkuAdminItemStatus = typeof TileSkuAdminItemStatus[keyof typeof TileSkuAdminItemStatus];


export const TileSkuAdminItemStatus = {
  PUBLISHED: 'PUBLISHED',
  DRAFT: 'DRAFT',
  NEEDS_COMPLETION: 'NEEDS_COMPLETION',
  DISABLED: 'DISABLED',
} as const;

export type TileSkuAdminItemMaterialCompleteness = typeof TileSkuAdminItemMaterialCompleteness[keyof typeof TileSkuAdminItemMaterialCompleteness];


export const TileSkuAdminItemMaterialCompleteness = {
  complete: 'complete',
  missing_main_image: 'missing_main_image',
  missing_images: 'missing_images',
  missing_videos: 'missing_videos',
} as const;

export interface TileSkuImageItem {
  id: number;
  object_key: string;
  url: string;
  is_main: boolean;
  sort_order: number;
}

export interface TileSkuVideoItem {
  id: number;
  object_key: string;
  url: string;
  file_name: string;
  file_size_bytes?: number | null;
  duration_seconds?: number | null;
  sort_order: number;
}

export interface TileSkuAdminItem {
  id: number;
  name: string;
  sku_code: string;
  brand_id: number;
  brand_name: string;
  category_id: number;
  category_name: string;
  size: string;
  surface_finish: string;
  color_family?: string | null;
  reference_price?: number | null;
  remark?: string | null;
  status: TileSkuAdminItemStatus;
  main_image_url?: string | null;
  image_count?: number;
  video_count?: number;
  has_main_image?: boolean;
  material_completeness: TileSkuAdminItemMaterialCompleteness;
  images?: TileSkuImageItem[];
  videos?: TileSkuVideoItem[];
  created_at: string;
  updated_at: string;
}

export interface ApiResponseTileSkuAdminItem {
  code?: number;
  message?: string;
  data?: TileSkuAdminItem | null;
}

export interface TileSkuAdminSummary {
  total: number;
  published_count: number;
  needs_completion_count: number;
  draft_count: number;
}

export type TileSkuAdminListDataPagination = {[key: string]: number};

export interface TileSkuAdminListData {
  items: TileSkuAdminItem[];
  pagination: TileSkuAdminListDataPagination;
  summary: TileSkuAdminSummary;
}

export interface ApiResponseTileSkuAdminListData {
  code?: number;
  message?: string;
  data?: TileSkuAdminListData | null;
}

export interface UploadResult {
  object_key: string;
  url: string;
}

export interface ApiResponseUploadResult {
  code?: number;
  message?: string;
  data?: UploadResult | null;
}

export interface UserAdminItem {
  id: string;
  username: string;
  display_name: string | null;
  role: string;
  status: string;
  avatar_object_key?: string | null;
  email?: string | null;
  phone?: string | null;
  last_login_at?: string | null;
  created_at: string;
}

export interface ApiResponseUserAdminItem {
  code?: number;
  message?: string;
  data?: UserAdminItem | null;
}

export interface UserAdminSummary {
  total: number;
  filtered: number;
  active_count: number;
  disabled_count: number;
}

export interface UserAdminListData {
  items: UserAdminItem[];
  page: number;
  page_size: number;
  total: number;
  summary: UserAdminSummary;
}

export interface ApiResponseUserAdminListData {
  code?: number;
  message?: string;
  data?: UserAdminListData | null;
}

export interface UserCreateData {
  user: UserAdminItem;
  initial_password: string;
}

export interface ApiResponseUserCreateData {
  code?: number;
  message?: string;
  data?: UserCreateData | null;
}

export interface ApiResponseUserProfile {
  code?: number;
  message?: string;
  data?: UserProfile | null;
}

export interface TileCategoryTreeNode {
  id: number;
  name: string;
  code: string;
  level: number;
  status: string;
  sku_count: number;
  children?: TileCategoryTreeNode[];
}

export interface ApiResponseListTileCategoryTreeNode {
  code?: number;
  message?: string;
  data?: TileCategoryTreeNode[] | null;
}

export interface BodyUploadBrandLogoApiV1AdminUploadsBrandLogosPost {
  file: Blob;
}

export interface BodyUploadImageApiV1AdminUploadsPost {
  file: Blob;
}

export interface BodyUploadTileImageApiV1AdminUploadsTileImagesPost {
  file: Blob;
}

export interface BodyUploadTileVideoApiV1AdminUploadsTileVideosPost {
  file: Blob;
}

export interface BrandCreateRequest {
  /**
     * @minLength 1
     * @maxLength 50
     */
  name: string;
  sort_order: number;
  short_name?: string | null;
  english_name?: string | null;
  logo_object_key?: string | null;
  description?: string | null;
}

export interface BrandUpdateRequest {
  /**
     * @minLength 1
     * @maxLength 50
     */
  name: string;
  sort_order: number;
  short_name?: string | null;
  english_name?: string | null;
  logo_object_key?: string | null;
  description?: string | null;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LoginRequest {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
  remember_me?: boolean;
}

export interface TileCategoryCreateRequest {
  parent_id?: number | null;
  /**
     * @minLength 1
     * @maxLength 30
     */
  name: string;
  /**
     * @minLength 1
     * @maxLength 32
     */
  code: string;
  sort_order: number;
  description?: string | null;
  status?: string;
}

export interface TileCategoryUpdateRequest {
  /**
     * @minLength 1
     * @maxLength 30
     */
  name: string;
  sort_order: number;
  description?: string | null;
}

export interface TileCreate {
  name: string;
  model: string;
  category?: string | null;
  color?: string | null;
  size?: string | null;
  description?: string | null;
}

export interface TileImage {
  object_key: string;
  url: string;
  is_main?: boolean;
}

export interface TileDetail {
  id: number;
  name: string;
  model: string;
  category?: string | null;
  color?: string | null;
  size?: string | null;
  description?: string | null;
  images?: TileImage[];
}

export interface TileListItem {
  id: number;
  name: string;
  model: string;
  category?: string | null;
  main_image_url?: string | null;
}

export type TileSkuCreateRequestSaveMode = typeof TileSkuCreateRequestSaveMode[keyof typeof TileSkuCreateRequestSaveMode];


export const TileSkuCreateRequestSaveMode = {
  draft: 'draft',
  create: 'create',
} as const;

export interface TileSkuImageInput {
  object_key: string;
  url: string;
  is_main?: boolean;
  sort_order?: number;
}

export interface TileSkuVideoInput {
  object_key: string;
  file_name: string;
  file_size_bytes?: number | null;
  duration_seconds?: number | null;
  sort_order?: number;
}

export interface TileSkuCreateRequest {
  save_mode?: TileSkuCreateRequestSaveMode;
  name: string;
  sku_code?: string | null;
  brand_id?: number | null;
  category_id?: number | null;
  size?: string | null;
  surface_finish?: string | null;
  color_family?: string | null;
  reference_price?: number | null;
  remark?: string | null;
  images?: TileSkuImageInput[];
  videos?: TileSkuVideoInput[];
}

export interface TileSkuUpdateRequest {
  name?: string | null;
  sku_code?: string | null;
  brand_id?: number | null;
  category_id?: number | null;
  size?: string | null;
  surface_finish?: string | null;
  color_family?: string | null;
  reference_price?: number | null;
  remark?: string | null;
  images?: TileSkuImageInput[] | null;
  videos?: TileSkuVideoInput[] | null;
}

export interface UserCreateRequest {
  /**
     * @minLength 4
     * @maxLength 32
     */
  username: string;
  display_name?: string | null;
  role: string;
  avatar_object_key?: string | null;
}

export interface UserStatusUpdateRequest {
  status: string;
}

export interface UserUpdateRequest {
  display_name?: string | null;
  role?: string | null;
  avatar_object_key?: string | null;
}

export type ListUsersApiV1AdminUsersGetParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 50
 */
page_size?: number;
keyword?: string | null;
role?: string | null;
status?: string | null;
login_filter?: string | null;
};

export type ListBrandsApiV1AdminBrandsGetParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
keyword?: string | null;
status?: string | null;
};

export type ListCategoriesApiV1AdminTileCategoriesGetParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 50
 */
page_size?: number;
keyword?: string | null;
status?: string | null;
level?: number | null;
parent_id?: number | null;
};

export type ListTileSkusApiV1AdminTileSkusGetParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
keyword?: string | null;
brand_id?: number | null;
category_id?: number | null;
status?: string | null;
material_completeness?: ListTileSkusApiV1AdminTileSkusGetMaterialCompleteness;
};

export type ListTileSkusApiV1AdminTileSkusGetMaterialCompleteness = typeof ListTileSkusApiV1AdminTileSkusGetMaterialCompleteness[keyof typeof ListTileSkusApiV1AdminTileSkusGetMaterialCompleteness] | null;


export const ListTileSkusApiV1AdminTileSkusGetMaterialCompleteness = {
  complete: 'complete',
  missing_main_image: 'missing_main_image',
  missing_images: 'missing_images',
  missing_videos: 'missing_videos',
} as const;

export type UploadTileImageApiV1AdminUploadsTileImagesPostParams = {
tile_id?: number | null;
};

export type UploadTileVideoApiV1AdminUploadsTileVideosPostParams = {
tile_id?: number | null;
};

export type HealthCheckHealthGet200 = {[key: string]: string};

export const getTilesFSTAPI = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary 用户登录
 */
const loginApiV1AuthLoginPost = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseLoginData>> => {
    return axiosInstance.post(
      `/api/v1/auth/login`,
      loginRequest,options
    );
  }

/**
 * @summary 获取当前用户
 */
const meApiV1AuthMeGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseUserProfile>> => {
    return axiosInstance.get(
      `/api/v1/auth/me`,options
    );
  }

/**
 * @summary 用户登出
 */
const logoutApiV1AuthLogoutPost = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseLogoutData>> => {
    return axiosInstance.post(
      `/api/v1/auth/logout`,
      undefined,options
    );
  }

/**
 * @summary 获取瓷砖列表
 */
const listTilesApiV1TilesGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TileListItem[]>> => {
    return axiosInstance.get(
      `/api/v1/tiles`,options
    );
  }

/**
 * @summary 获取瓷砖详情
 */
const getTileApiV1TilesTileIdGet = (
    tileId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TileDetail>> => {
    return axiosInstance.get(
      `/api/v1/tiles/${tileId}`,options
    );
  }

/**
 * @summary 创建瓷砖
 */
const createTileApiV1AdminTilesPost = (
    tileCreate: TileCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TileDetail>> => {
    return axiosInstance.post(
      `/api/v1/admin/tiles`,
      tileCreate,options
    );
  }

/**
 * @summary 用户列表
 */
const listUsersApiV1AdminUsersGet = (
    params?: ListUsersApiV1AdminUsersGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseUserAdminListData>> => {
    return axiosInstance.get(
      `/api/v1/admin/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary 创建用户
 */
const createUserApiV1AdminUsersPost = (
    userCreateRequest: UserCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseUserCreateData>> => {
    return axiosInstance.post(
      `/api/v1/admin/users`,
      userCreateRequest,options
    );
  }

/**
 * @summary 用户详情
 */
const getUserApiV1AdminUsersUserIdGet = (
    userId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseUserAdminItem>> => {
    return axiosInstance.get(
      `/api/v1/admin/users/${userId}`,options
    );
  }

/**
 * @summary 更新用户
 */
const updateUserApiV1AdminUsersUserIdPatch = (
    userId: string,
    userUpdateRequest: UserUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseUserAdminItem>> => {
    return axiosInstance.patch(
      `/api/v1/admin/users/${userId}`,
      userUpdateRequest,options
    );
  }

/**
 * @summary 重置密码
 */
const resetPasswordApiV1AdminUsersUserIdResetPasswordPost = (
    userId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseResetPasswordData>> => {
    return axiosInstance.post(
      `/api/v1/admin/users/${userId}/reset-password`,
      undefined,options
    );
  }

/**
 * @summary 更新用户状态
 */
const updateUserStatusApiV1AdminUsersUserIdStatusPatch = (
    userId: string,
    userStatusUpdateRequest: UserStatusUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseUserAdminItem>> => {
    return axiosInstance.patch(
      `/api/v1/admin/users/${userId}/status`,
      userStatusUpdateRequest,options
    );
  }

/**
 * @summary 品牌列表
 */
const listBrandsApiV1AdminBrandsGet = (
    params?: ListBrandsApiV1AdminBrandsGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseBrandAdminListData>> => {
    return axiosInstance.get(
      `/api/v1/admin/brands`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary 创建品牌
 */
const createBrandApiV1AdminBrandsPost = (
    brandCreateRequest: BrandCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseBrandAdminItem>> => {
    return axiosInstance.post(
      `/api/v1/admin/brands`,
      brandCreateRequest,options
    );
  }

/**
 * @summary 品牌详情
 */
const getBrandApiV1AdminBrandsBrandIdGet = (
    brandId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseBrandAdminItem>> => {
    return axiosInstance.get(
      `/api/v1/admin/brands/${brandId}`,options
    );
  }

/**
 * @summary 更新品牌
 */
const updateBrandApiV1AdminBrandsBrandIdPut = (
    brandId: number,
    brandUpdateRequest: BrandUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseBrandAdminItem>> => {
    return axiosInstance.put(
      `/api/v1/admin/brands/${brandId}`,
      brandUpdateRequest,options
    );
  }

/**
 * @summary 删除品牌
 */
const deleteBrandApiV1AdminBrandsBrandIdDelete = (
    brandId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseNoneType>> => {
    return axiosInstance.delete(
      `/api/v1/admin/brands/${brandId}`,options
    );
  }

/**
 * @summary 启用品牌
 */
const enableBrandApiV1AdminBrandsBrandIdEnablePost = (
    brandId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseBrandAdminItem>> => {
    return axiosInstance.post(
      `/api/v1/admin/brands/${brandId}/enable`,
      undefined,options
    );
  }

/**
 * @summary 停用品牌
 */
const disableBrandApiV1AdminBrandsBrandIdDisablePost = (
    brandId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseBrandAdminItem>> => {
    return axiosInstance.post(
      `/api/v1/admin/brands/${brandId}/disable`,
      undefined,options
    );
  }

/**
 * @summary 类目树
 */
const getCategoryTreeApiV1AdminTileCategoriesTreeGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseListTileCategoryTreeNode>> => {
    return axiosInstance.get(
      `/api/v1/admin/tile-categories/tree`,options
    );
  }

/**
 * @summary 类目列表
 */
const listCategoriesApiV1AdminTileCategoriesGet = (
    params?: ListCategoriesApiV1AdminTileCategoriesGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseTileCategoryAdminListData>> => {
    return axiosInstance.get(
      `/api/v1/admin/tile-categories`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary 创建类目
 */
const createCategoryApiV1AdminTileCategoriesPost = (
    tileCategoryCreateRequest: TileCategoryCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseTileCategoryAdminItem>> => {
    return axiosInstance.post(
      `/api/v1/admin/tile-categories`,
      tileCategoryCreateRequest,options
    );
  }

/**
 * @summary 类目详情
 */
const getCategoryApiV1AdminTileCategoriesCategoryIdGet = (
    categoryId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseTileCategoryAdminItem>> => {
    return axiosInstance.get(
      `/api/v1/admin/tile-categories/${categoryId}`,options
    );
  }

/**
 * @summary 更新类目
 */
const updateCategoryApiV1AdminTileCategoriesCategoryIdPut = (
    categoryId: number,
    tileCategoryUpdateRequest: TileCategoryUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseTileCategoryAdminItem>> => {
    return axiosInstance.put(
      `/api/v1/admin/tile-categories/${categoryId}`,
      tileCategoryUpdateRequest,options
    );
  }

/**
 * @summary 删除类目
 */
const deleteCategoryApiV1AdminTileCategoriesCategoryIdDelete = (
    categoryId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseNoneType>> => {
    return axiosInstance.delete(
      `/api/v1/admin/tile-categories/${categoryId}`,options
    );
  }

/**
 * @summary 启用类目
 */
const enableCategoryApiV1AdminTileCategoriesCategoryIdEnablePost = (
    categoryId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseTileCategoryAdminItem>> => {
    return axiosInstance.post(
      `/api/v1/admin/tile-categories/${categoryId}/enable`,
      undefined,options
    );
  }

/**
 * @summary 停用类目
 */
const disableCategoryApiV1AdminTileCategoriesCategoryIdDisablePost = (
    categoryId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseTileCategoryAdminItem>> => {
    return axiosInstance.post(
      `/api/v1/admin/tile-categories/${categoryId}/disable`,
      undefined,options
    );
  }

/**
 * @summary SKU 列表
 */
const listTileSkusApiV1AdminTileSkusGet = (
    params?: ListTileSkusApiV1AdminTileSkusGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseTileSkuAdminListData>> => {
    return axiosInstance.get(
      `/api/v1/admin/tile-skus`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary 创建 SKU
 */
const createTileSkuApiV1AdminTileSkusPost = (
    tileSkuCreateRequest: TileSkuCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseTileSkuAdminItem>> => {
    return axiosInstance.post(
      `/api/v1/admin/tile-skus`,
      tileSkuCreateRequest,options
    );
  }

/**
 * @summary SKU 详情
 */
const getTileSkuApiV1AdminTileSkusTileIdGet = (
    tileId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseTileSkuAdminItem>> => {
    return axiosInstance.get(
      `/api/v1/admin/tile-skus/${tileId}`,options
    );
  }

/**
 * @summary 更新 SKU
 */
const updateTileSkuApiV1AdminTileSkusTileIdPut = (
    tileId: number,
    tileSkuUpdateRequest: TileSkuUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseTileSkuAdminItem>> => {
    return axiosInstance.put(
      `/api/v1/admin/tile-skus/${tileId}`,
      tileSkuUpdateRequest,options
    );
  }

/**
 * @summary 删除 SKU
 */
const deleteTileSkuApiV1AdminTileSkusTileIdDelete = (
    tileId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseNoneType>> => {
    return axiosInstance.delete(
      `/api/v1/admin/tile-skus/${tileId}`,options
    );
  }

/**
 * @summary 上架 SKU
 */
const publishTileSkuApiV1AdminTileSkusTileIdPublishPost = (
    tileId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseTileSkuAdminItem>> => {
    return axiosInstance.post(
      `/api/v1/admin/tile-skus/${tileId}/publish`,
      undefined,options
    );
  }

/**
 * @summary 下架 SKU
 */
const unpublishTileSkuApiV1AdminTileSkusTileIdUnpublishPost = (
    tileId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseTileSkuAdminItem>> => {
    return axiosInstance.post(
      `/api/v1/admin/tile-skus/${tileId}/unpublish`,
      undefined,options
    );
  }

/**
 * @summary 上传头像
 */
const uploadImageApiV1AdminUploadsPost = (
    bodyUploadImageApiV1AdminUploadsPost: BodyUploadImageApiV1AdminUploadsPost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseUploadResult>> => {const formData = new FormData();
formData.append(`file`, bodyUploadImageApiV1AdminUploadsPost.file);

    return axiosInstance.post(
      `/api/v1/admin/uploads`,
      formData,options
    );
  }

/**
 * @summary 上传品牌 Logo
 */
const uploadBrandLogoApiV1AdminUploadsBrandLogosPost = (
    bodyUploadBrandLogoApiV1AdminUploadsBrandLogosPost: BodyUploadBrandLogoApiV1AdminUploadsBrandLogosPost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseUploadResult>> => {const formData = new FormData();
formData.append(`file`, bodyUploadBrandLogoApiV1AdminUploadsBrandLogosPost.file);

    return axiosInstance.post(
      `/api/v1/admin/uploads/brand-logos`,
      formData,options
    );
  }

/**
 * @summary 上传 SKU 图片
 */
const uploadTileImageApiV1AdminUploadsTileImagesPost = (
    bodyUploadTileImageApiV1AdminUploadsTileImagesPost: BodyUploadTileImageApiV1AdminUploadsTileImagesPost,
    params?: UploadTileImageApiV1AdminUploadsTileImagesPostParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseUploadResult>> => {const formData = new FormData();
formData.append(`file`, bodyUploadTileImageApiV1AdminUploadsTileImagesPost.file);

    return axiosInstance.post(
      `/api/v1/admin/uploads/tile-images`,
      formData,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary 上传 SKU 视频
 */
const uploadTileVideoApiV1AdminUploadsTileVideosPost = (
    bodyUploadTileVideoApiV1AdminUploadsTileVideosPost: BodyUploadTileVideoApiV1AdminUploadsTileVideosPost,
    params?: UploadTileVideoApiV1AdminUploadsTileVideosPostParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseUploadResult>> => {const formData = new FormData();
formData.append(`file`, bodyUploadTileVideoApiV1AdminUploadsTileVideosPost.file);

    return axiosInstance.post(
      `/api/v1/admin/uploads/tile-videos`,
      formData,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Health Check
 */
const healthCheckHealthGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HealthCheckHealthGet200>> => {
    return axiosInstance.get(
      `/health`,options
    );
  }

return {loginApiV1AuthLoginPost,meApiV1AuthMeGet,logoutApiV1AuthLogoutPost,listTilesApiV1TilesGet,getTileApiV1TilesTileIdGet,createTileApiV1AdminTilesPost,listUsersApiV1AdminUsersGet,createUserApiV1AdminUsersPost,getUserApiV1AdminUsersUserIdGet,updateUserApiV1AdminUsersUserIdPatch,resetPasswordApiV1AdminUsersUserIdResetPasswordPost,updateUserStatusApiV1AdminUsersUserIdStatusPatch,listBrandsApiV1AdminBrandsGet,createBrandApiV1AdminBrandsPost,getBrandApiV1AdminBrandsBrandIdGet,updateBrandApiV1AdminBrandsBrandIdPut,deleteBrandApiV1AdminBrandsBrandIdDelete,enableBrandApiV1AdminBrandsBrandIdEnablePost,disableBrandApiV1AdminBrandsBrandIdDisablePost,getCategoryTreeApiV1AdminTileCategoriesTreeGet,listCategoriesApiV1AdminTileCategoriesGet,createCategoryApiV1AdminTileCategoriesPost,getCategoryApiV1AdminTileCategoriesCategoryIdGet,updateCategoryApiV1AdminTileCategoriesCategoryIdPut,deleteCategoryApiV1AdminTileCategoriesCategoryIdDelete,enableCategoryApiV1AdminTileCategoriesCategoryIdEnablePost,disableCategoryApiV1AdminTileCategoriesCategoryIdDisablePost,listTileSkusApiV1AdminTileSkusGet,createTileSkuApiV1AdminTileSkusPost,getTileSkuApiV1AdminTileSkusTileIdGet,updateTileSkuApiV1AdminTileSkusTileIdPut,deleteTileSkuApiV1AdminTileSkusTileIdDelete,publishTileSkuApiV1AdminTileSkusTileIdPublishPost,unpublishTileSkuApiV1AdminTileSkusTileIdUnpublishPost,uploadImageApiV1AdminUploadsPost,uploadBrandLogoApiV1AdminUploadsBrandLogosPost,uploadTileImageApiV1AdminUploadsTileImagesPost,uploadTileVideoApiV1AdminUploadsTileVideosPost,healthCheckHealthGet}};
export type LoginApiV1AuthLoginPostResult = AxiosResponse<ApiResponseLoginData>
export type MeApiV1AuthMeGetResult = AxiosResponse<ApiResponseUserProfile>
export type LogoutApiV1AuthLogoutPostResult = AxiosResponse<ApiResponseLogoutData>
export type ListTilesApiV1TilesGetResult = AxiosResponse<TileListItem[]>
export type GetTileApiV1TilesTileIdGetResult = AxiosResponse<TileDetail>
export type CreateTileApiV1AdminTilesPostResult = AxiosResponse<TileDetail>
export type ListUsersApiV1AdminUsersGetResult = AxiosResponse<ApiResponseUserAdminListData>
export type CreateUserApiV1AdminUsersPostResult = AxiosResponse<ApiResponseUserCreateData>
export type GetUserApiV1AdminUsersUserIdGetResult = AxiosResponse<ApiResponseUserAdminItem>
export type UpdateUserApiV1AdminUsersUserIdPatchResult = AxiosResponse<ApiResponseUserAdminItem>
export type ResetPasswordApiV1AdminUsersUserIdResetPasswordPostResult = AxiosResponse<ApiResponseResetPasswordData>
export type UpdateUserStatusApiV1AdminUsersUserIdStatusPatchResult = AxiosResponse<ApiResponseUserAdminItem>
export type ListBrandsApiV1AdminBrandsGetResult = AxiosResponse<ApiResponseBrandAdminListData>
export type CreateBrandApiV1AdminBrandsPostResult = AxiosResponse<ApiResponseBrandAdminItem>
export type GetBrandApiV1AdminBrandsBrandIdGetResult = AxiosResponse<ApiResponseBrandAdminItem>
export type UpdateBrandApiV1AdminBrandsBrandIdPutResult = AxiosResponse<ApiResponseBrandAdminItem>
export type DeleteBrandApiV1AdminBrandsBrandIdDeleteResult = AxiosResponse<ApiResponseNoneType>
export type EnableBrandApiV1AdminBrandsBrandIdEnablePostResult = AxiosResponse<ApiResponseBrandAdminItem>
export type DisableBrandApiV1AdminBrandsBrandIdDisablePostResult = AxiosResponse<ApiResponseBrandAdminItem>
export type GetCategoryTreeApiV1AdminTileCategoriesTreeGetResult = AxiosResponse<ApiResponseListTileCategoryTreeNode>
export type ListCategoriesApiV1AdminTileCategoriesGetResult = AxiosResponse<ApiResponseTileCategoryAdminListData>
export type CreateCategoryApiV1AdminTileCategoriesPostResult = AxiosResponse<ApiResponseTileCategoryAdminItem>
export type GetCategoryApiV1AdminTileCategoriesCategoryIdGetResult = AxiosResponse<ApiResponseTileCategoryAdminItem>
export type UpdateCategoryApiV1AdminTileCategoriesCategoryIdPutResult = AxiosResponse<ApiResponseTileCategoryAdminItem>
export type DeleteCategoryApiV1AdminTileCategoriesCategoryIdDeleteResult = AxiosResponse<ApiResponseNoneType>
export type EnableCategoryApiV1AdminTileCategoriesCategoryIdEnablePostResult = AxiosResponse<ApiResponseTileCategoryAdminItem>
export type DisableCategoryApiV1AdminTileCategoriesCategoryIdDisablePostResult = AxiosResponse<ApiResponseTileCategoryAdminItem>
export type ListTileSkusApiV1AdminTileSkusGetResult = AxiosResponse<ApiResponseTileSkuAdminListData>
export type CreateTileSkuApiV1AdminTileSkusPostResult = AxiosResponse<ApiResponseTileSkuAdminItem>
export type GetTileSkuApiV1AdminTileSkusTileIdGetResult = AxiosResponse<ApiResponseTileSkuAdminItem>
export type UpdateTileSkuApiV1AdminTileSkusTileIdPutResult = AxiosResponse<ApiResponseTileSkuAdminItem>
export type DeleteTileSkuApiV1AdminTileSkusTileIdDeleteResult = AxiosResponse<ApiResponseNoneType>
export type PublishTileSkuApiV1AdminTileSkusTileIdPublishPostResult = AxiosResponse<ApiResponseTileSkuAdminItem>
export type UnpublishTileSkuApiV1AdminTileSkusTileIdUnpublishPostResult = AxiosResponse<ApiResponseTileSkuAdminItem>
export type UploadImageApiV1AdminUploadsPostResult = AxiosResponse<ApiResponseUploadResult>
export type UploadBrandLogoApiV1AdminUploadsBrandLogosPostResult = AxiosResponse<ApiResponseUploadResult>
export type UploadTileImageApiV1AdminUploadsTileImagesPostResult = AxiosResponse<ApiResponseUploadResult>
export type UploadTileVideoApiV1AdminUploadsTileVideosPostResult = AxiosResponse<ApiResponseUploadResult>
export type HealthCheckHealthGetResult = AxiosResponse<HealthCheckHealthGet200>
