/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * 瓷砖信息管理平台 API
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface UserProfile {
  id: string;
  username: string;
  display_name: string;
  role: string;
  status: string;
}

export interface LoginData {
  access_token: string;
  token_type?: string;
  expires_in: number;
  user: UserProfile;
}

export interface ApiResponseLoginData {
  code?: number;
  message?: string;
  data?: LoginData | null;
}

export interface LogoutData {
  success?: boolean;
}

export interface ApiResponseLogoutData {
  code?: number;
  message?: string;
  data?: LogoutData | null;
}

export interface ApiResponseUserProfile {
  code?: number;
  message?: string;
  data?: UserProfile | null;
}

export interface BodyUploadImageApiV1AdminUploadsPost {
  file: Blob;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LoginRequest {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
  remember_me?: boolean;
}

export interface TileCreate {
  name: string;
  model: string;
  category?: string | null;
  color?: string | null;
  size?: string | null;
  description?: string | null;
}

export interface TileImage {
  object_key: string;
  url: string;
  is_main?: boolean;
}

export interface TileDetail {
  id: number;
  name: string;
  model: string;
  category?: string | null;
  color?: string | null;
  size?: string | null;
  description?: string | null;
  images?: TileImage[];
}

export interface TileListItem {
  id: number;
  name: string;
  model: string;
  category?: string | null;
  main_image_url?: string | null;
}

export interface UploadResult {
  object_key: string;
  url: string;
}

export type HealthCheckHealthGet200 = {[key: string]: string};

export const getApi = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Login
 */
const loginApiV1AuthLoginPost = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseLoginData>> => {
    return axiosInstance.post(
      `/api/v1/auth/login`,
      loginRequest,options
    );
  }

/**
 * @summary Me
 */
const meApiV1AuthMeGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseUserProfile>> => {
    return axiosInstance.get(
      `/api/v1/auth/me`,options
    );
  }

/**
 * @summary Logout
 */
const logoutApiV1AuthLogoutPost = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseLogoutData>> => {
    return axiosInstance.post(
      `/api/v1/auth/logout`,
      undefined,options
    );
  }

/**
 * @summary List Tiles
 */
const listTilesApiV1TilesGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TileListItem[]>> => {
    return axiosInstance.get(
      `/api/v1/tiles`,options
    );
  }

/**
 * @summary Get Tile
 */
const getTileApiV1TilesTileIdGet = (
    tileId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TileDetail>> => {
    return axiosInstance.get(
      `/api/v1/tiles/${tileId}`,options
    );
  }

/**
 * @summary Create Tile
 */
const createTileApiV1AdminTilesPost = (
    tileCreate: TileCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TileDetail>> => {
    return axiosInstance.post(
      `/api/v1/admin/tiles`,
      tileCreate,options
    );
  }

/**
 * @summary Upload Image
 */
const uploadImageApiV1AdminUploadsPost = (
    bodyUploadImageApiV1AdminUploadsPost: BodyUploadImageApiV1AdminUploadsPost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UploadResult>> => {const formData = new FormData();
formData.append(`file`, bodyUploadImageApiV1AdminUploadsPost.file);

    return axiosInstance.post(
      `/api/v1/admin/uploads`,
      formData,options
    );
  }

/**
 * @summary Health Check
 */
const healthCheckHealthGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HealthCheckHealthGet200>> => {
    return axiosInstance.get(
      `/health`,options
    );
  }

return {loginApiV1AuthLoginPost,meApiV1AuthMeGet,logoutApiV1AuthLogoutPost,listTilesApiV1TilesGet,getTileApiV1TilesTileIdGet,createTileApiV1AdminTilesPost,uploadImageApiV1AdminUploadsPost,healthCheckHealthGet}};
export type LoginApiV1AuthLoginPostResult = AxiosResponse<ApiResponseLoginData>
export type MeApiV1AuthMeGetResult = AxiosResponse<ApiResponseUserProfile>
export type LogoutApiV1AuthLogoutPostResult = AxiosResponse<ApiResponseLogoutData>
export type ListTilesApiV1TilesGetResult = AxiosResponse<TileListItem[]>
export type GetTileApiV1TilesTileIdGetResult = AxiosResponse<TileDetail>
export type CreateTileApiV1AdminTilesPostResult = AxiosResponse<TileDetail>
export type UploadImageApiV1AdminUploadsPostResult = AxiosResponse<UploadResult>
export type HealthCheckHealthGetResult = AxiosResponse<HealthCheckHealthGet200>
