/**
 * Sync TypeScript design tokens to Web CSS variables.
 *
 * Usage: cd src/web && pnpm sync:tokens
 * Note: Commit tokens.generated.css after token changes (Docker build uses src/web context only).
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateTokensCss } from '../../shared/design-system/tokens/css.ts';

import { miniappPriceTokens } from '../../shared/design-system/tokens/colors.ts';

const webDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = path.join(webDir, 'src/styles/tokens.generated.css');

writeFileSync(outputPath, `${generateTokensCss()}\n`, 'utf8');
console.log(`Wrote ${outputPath}`);

const priceVars = Object.entries(miniappPriceTokens)
  .map(([key, value]) => `  --price-${key}: ${value};`).join('\n');
const priceCss = `/* Generated by pnpm sync:tokens. Source: shared/design-system/tokens/colors.ts */
.price-theme {
${priceVars}
}
`;
const miniappStyles = path.resolve(webDir, '../miniapp/styles');
mkdirSync(miniappStyles, { recursive: true });
writeFileSync(path.join(miniappStyles, 'price.generated.wxss'), priceCss, 'utf8');
